### PR TITLE
Fix COPY FROM STDIN handling

### LINKED ISSUE #1023: closing because: client disconnect while server was not ready when set max_prepared_statement>0
When I set max_prepared_statement > 0 I get following errors and no client is able to connect.

```
	2024-02-13 11:42:10	
2024-02-13 10:42:10.916 UTC [1] LOG S-0x5632ccbe4050: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=0s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.916 UTC [1] LOG C-0x5632ccbd9830: timestore/timestore@100.101.246.171:38244 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.791 UTC [1] LOG S-0x5632ccbe4050: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=0s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.791 UTC [1] LOG C-0x5632ccbd9830: timestore/timestore@100.99.85.34:39604 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.468 UTC [1] LOG S-0x5632ccbe4050: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=2s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.468 UTC [1] LOG C-0x5632ccbd9830: timestore/timestore@100.117.54.92:33762 closing because: client unexpected eof (age=15s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.294 UTC [1] LOG S-0x5632ccbe2d80: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=2s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.294 UTC [1] LOG C-0x5632ccbdb5c0: timestore/timestore@100.117.54.112:33046 closing because: client unexpected eof (age=8s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.061 UTC [1] LOG S-0x5632ccbe3da0: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=1s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.061 UTC [1] LOG C-0x5632ccbda850: timestore/timestore@100.101.246.167:38486 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.053 UTC [1] LOG S-0x5632ccbe3af0: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=1s)
	
2024-02-13 11:42:10	
2024-02-13 10:42:10.053 UTC [1] LOG C-0x5632ccbda850: timestore/timestore@100.101.246.171:38238 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:08	
2024-02-13 10:42:08.783 UTC [1] LOG S-0x5632ccbe2820: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=0s)
	
2024-02-13 11:42:08	
2024-02-13 10:42:08.783 UTC [1] LOG C-0x5632ccbda850: timestore/timestore@100.99.85.34:39598 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:07	
2024-02-13 10:42:07.825 UTC [1] LOG S-0x5632ccbe3da0: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=0s)
	
2024-02-13 11:42:07	
2024-02-13 10:42:07.825 UTC [1] LOG C-0x5632ccbdadb0: timestore/timestore@100.101.246.167:38474 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:07	
2024-02-13 10:42:07.193 UTC [1] LOG S-0x5632ccbe3da0: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=4s)
	
2024-02-13 11:42:07	
2024-02-13 10:42:07.193 UTC [1] LOG C-0x5632ccbdadb0: timestore/timestore@100.101.246.167:38464 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:05	
2024-02-13 10:42:05.335 UTC [1] LOG S-0x5632ccbe2820: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=3s)
	
2024-02-13 11:42:05	
2024-02-13 10:42:05.335 UTC [1] LOG C-0x5632ccbdadb0: timestore/timestore@100.117.54.112:33034 closing because: client unexpected eof (age=3s)
	
2024-02-13 11:42:04	
2024-02-13 10:42:04.810 UTC [1] LOG S-0x5632ccbe3af0: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=2s)
	
2024-02-13 11:42:04	
2024-02-13 10:42:04.810 UTC [1] LOG C-0x5632ccbdb870: timestore/timestore@100.117.54.112:33022 closing because: client unexpected eof (age=2s)
	
2024-02-13 11:42:04	
2024-02-13 10:42:04.521 UTC [1] LOG S-0x5632ccbe4050: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=2s)
	
2024-02-13 11:42:04	
2024-02-13 10:42:04.521 UTC [1] LOG C-0x5632ccbda850: timestore/timestore@100.117.54.92:33784 closing because: client unexpected eof (age=9s)
	
2024-02-13 11:42:02	
2024-02-13 10:42:02.898 UTC [1] LOG S-0x5632ccbe2d80: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=0s)
	
2024-02-13 11:42:02	
2024-02-13 10:42:02.897 UTC [1] LOG C-0x5632ccbdc080: timestore/timestore@100.117.54.112:33008 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:02	
2024-02-13 10:42:02.224 UTC [1] LOG S-0x5632ccbe3da0: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=0s)
	
2024-02-13 11:42:02	
2024-02-13 10:42:02.224 UTC [1] LOG C-0x5632ccbdb060: timestore/timestore@100.99.85.34:43554 closing because: client unexpected eof (age=0s)
	
2024-02-13 11:42:02	
2024-02-13 10:42:02.062 UTC [1] LOG S-0x5632ccbe4050: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=1s)
	
2024-02-13 11:42:02	
2024-02-13 10:42:02.062 UTC [1] LOG C-0x5632ccbdb870: timestore/timestore@100.117.54.112:46486 closing because: client unexpected eof (age=1s)
	
2024-02-13 11:42:01	
2024-02-13 10:42:01.066 UTC [1] LOG S-0x5632ccbe3af0: timestore/timestore@unix:5432 closing because: client disconnect while server was not ready (age=11s)
	
2024-02-13 11:42:01	
2024-02-13 10:42:01.066 UTC [1] LOG C-0x5632ccbdc080: timestore/timestore@100.101.246.167:45164 closing because: client unexpected eof (age=19s)
````

My options:
```
SHOW CONFIG;
            key            |                                                                                                             value                                                                                                             |                        default                         | changeable
---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------+------------
 admin_users               |                                                                                                                                                                                                                               |                                                        | yes
 application_name_add_host | 0                                                                                                                                                                                                                             | 0                                                      | yes
 auth_dbname               |                                                                                                                                                                                                                               |                                                        | yes
 auth_file                 |                                                                                                                                                                                                                               |                                                        | yes
 auth_hba_file             | /etc/pgbouncer/pg_hba.conf                                                                                                                                                                                                    |                                                        | yes
 auth_query                | SELECT rolname, rolpassword FROM pg_catalog.set_config('application_name', 'pgbouncer authentication', false) CROSS JOIN pg_catalog.pg_authid WHERE rolname = $1 AND NOT rolsuper AND NOT rolreplication AND NOT rolbypassrls | SELECT usename, passwd FROM pg_shadow WHERE usename=$1 | yes
 auth_type                 | hba                                                                                                                                                                                                                           | md5                                                    | yes
 auth_user                 | postgres                                                                                                                                                                                                                      |                                                        | yes
 autodb_idle_timeout       | 3600                                                                                                                                                                                                                          | 3600                                                   | yes
 client_idle_timeout       | 0                                                                                                                                                                                                                             | 0                                                      | yes
 client_login_timeout      | 60                                                                                                                                                                                                                            | 60                                                     | yes
 client_tls_ca_file        |                                                                                                                                                                                                                               |                                                        | yes
 client_tls_cert_file      | /etc/certificate/tls.crt                                                                                                                                                                                                      |                                                        | yes
 client_tls_ciphers        | default                                                                                                                                                                                                                       | default                                                | yes
 client_tls_dheparams      | auto                                                                                                                                                                                                                          | auto                                                   | yes
 client_tls_ecdhcurve      | auto                                                                                                                                                                                                                          | auto                                                   | yes
 client_tls_key_file       | /etc/certificate/tls.key                                                                                                                                                                                                      |                                                        | yes
 client_tls_protocols      | secure                                                                                                                                                                                                                        | secure                                                 | yes
 client_tls_sslmode        | disable                                                                                                                                                                                                                       | disable                                                | yes
 conffile                  | /etc/pgbouncer/pgbouncer-sidecar.ini                                                                                                                                                                                          |                                                        | yes
 default_pool_size         | 45                                                                                                                                                                                                                            | 20                                                     | yes
 disable_pqexec            | 0                                                                                                                                                                                                                             | 0                                                      | no
 dns_max_ttl               | 15                                                                                                                                                                                                                            | 15                                                     | yes
 dns_nxdomain_ttl          | 15                                                                                                                                                                                                                            | 15                                                     | yes
 dns_zone_check_period     | 0                                                                                                                                                                                                                             | 0                                                      | yes
 idle_transaction_timeout  | 0                                                                                                                                                                                                                             | 0                                                      | yes
 ignore_startup_parameters |                                                                                                                                                                                                                               |                                                        | yes
 job_name                  | pgbouncer                                                                                                                                                                                                                     | pgbouncer                                              | no
 listen_addr               | *                                                                                                                                                                                                                             |                                                        | no
 listen_backlog            | 128                                                                                                                                                                                                                           | 128                                                    | no
 listen_port               | 6432                                                                                                                                                                                                                          | 6432                                                   | no
 log_connections           | 1                                                                                                                                                                                                                             | 1                                                      | yes
 log_disconnections        | 1                                                                                                                                                                                                                             | 1                                                      | yes
 log_pooler_errors         | 1                                                                                                                                                                                                                             | 1                                                      | yes
 log_stats                 | 1                                                                                                                                                                                                                             | 1                                                      | yes
 logfile                   |                                                                                                                                                                                                                               |                                                        | yes
 max_client_conn           | 1000                                                                                                                                                                                                                          | 100                                                    | yes
 max_db_connections        | 0                                                                                                                                                                                                                             | 0                                                      | yes
 max_packet_size           | 2147483647                                                                                                                                                                                                                    | 2147483647                                             | yes
 max_prepared_statements   | 0                                                                                                                                                                                                                             | 0                                                      | yes
 max_user_connections      | 0                                                                                                                                                                                                                             | 0                                                      | yes
 min_pool_size             | 0                                                                                                                                                                                                                             | 0                                                      | yes
 peer_id                   | 0                                                                                                                                                                                                                             | 0                                                      | yes
 pidfile                   | /var/run/postgresql/pgbouncer.pid                                                                                                                                                                                             |                                                        | no
 pkt_buf                   | 4096                                                                                                                                                                                                                          | 4096                                                   | no
 pool_mode                 | transaction                                                                                                                                                                                                                   | session                                                | yes
 query_timeout             | 0                                                                                                                                                                                                                             | 0                                                      | yes
 query_wait_timeout        | 120                                                                                                                                                                                                                           | 120                                                    | yes
 cancel_wait_timeout       | 10                                                                                                                                                                                                                            | 10                                                     | yes
 reserve_pool_size         | 0                                                                                                                                                                                                                             | 0                                                      | yes
 reserve_pool_timeout      | 30                                                                                                                                                                                                                            | 5                                                      | yes
 resolv_conf               |                                                                                                                                                                                                                               |                                                        | no
 sbuf_loopcnt              | 5                                                                                                                                                                                                                             | 5                                                      | yes
 server_check_delay        | 30                                                                                                                                                                                                                            | 30                                                     | yes
 server_check_query        | select 1                                                                                                                                                                                                                      | select 1                                               | yes
 server_connect_timeout    | 15                                                                                                                                                                                                                            | 15                                                     | yes
 server_fast_close         | 0                                                                                                                                                                                                                             | 0                                                      | yes
 server_idle_timeout       | 600                                                                                                                                                                                                                           | 600                                                    | yes
 server_lifetime           | 3600                                                                                                                                                                                                                          | 3600                                                   | yes
 server_login_retry        | 15                                                                                                                                                                                                                            | 15                                                     | yes
 server_reset_query        | DEALLOCATE ALL                                                                                                                                                                                                                | DISCARD ALL                                            | yes
 server_reset_query_always | 1                                                                                                                                                                                                                             | 0                                                      | yes
 server_round_robin        | 0                                                                                                                                                                                                                             | 0                                                      | yes
 server_tls_ca_file        |                                                                                                                                                                                                                               |                                                        | yes
 server_tls_cert_file      |                                                                                                                                                                                                                               |                                                        | yes
 server_tls_ciphers        | default                                                                                                                                                                                                                       | default                                                | yes
 server_tls_key_file       |                                                                                                                                                                                                                               |                                                        | yes
 server_tls_protocols      | secure                                                                                                                                                                                                                        | secure                                                 | yes
 server_tls_sslmode        | disable                                                                                                                                                                                                                       | prefer                                                 | yes
 so_reuseport              | 0                                                                                                                                                                                                                             | 0                                                      | no
 stats_period              | 60                                                                                                                                                                                                                            | 60                                                     | yes
 stats_users               |                                                                                                                                                                                                                               |                                                        | yes
 suspend_timeout           | 10                                                                                                                                                                                                                            | 10                                                     | yes
 syslog                    | 0                                                                                                                                                                                                                             | 0                                                      | yes
 syslog_facility           | daemon                                                                                                                                                                                                                        | daemon                                                 | yes
 syslog_ident              | pgbouncer                                                                                                                                                                                                                     | pgbouncer                                              | yes
 tcp_defer_accept          | 1                                                                                                                                                                                                                             | 1                                                      | yes
 tcp_keepalive             | 1                                                                                                                                                                                                                             | 1                                                      | yes
 tcp_keepcnt               | 0                                                                                                                                                                                                                             | 0                                                      | yes
 tcp_keepidle              | 0                                                                                                                                                                                                                             | 0                                                      | yes
 tcp_keepintvl             | 0                                                                                                                                                                                                                             | 0                                                      | yes
 tcp_socket_buffer         | 0                                                                                                                                                                                                                             | 0                                                      | yes
 tcp_user_timeout          | 0                                                                                                                                                                                                                             | 0                                                      | yes
 track_extra_parameters    | IntervalStyle                                                                                                                                                                                                                 | IntervalStyle                                          | no
 unix_socket_dir           | /var/run/postgresql                                                                                                                                                                                                           | /tmp                                                   | no
 unix_socket_group         |                                                                                                                                                                                                                               |                                                        | no
 unix_socket_mode          | 493                                                                                                                                                                                                                           | 0777                                                   | no
 user                      |                                                                                                                                                                                                                               |                                                        | no
 verbose                   | 0                                                                                                                                                                                                                             |                                                        | yes
(89 rows)
```

I also tried changing `server_reset_query` and `server_reset_query_always` but with no effect.
When I set max_prepared_statement=0 problem disappears.

### LINKED ISSUE #1024: FIXME: query end, but query_start == 0
I know this issue appeared several times, but from the issues I found I concluded you assume the issue to be fixed.
We very much see this not to be the case in many latest versions.
Currently we use:
```
PgBouncer 1.22.0
libevent 2.1.12-stable
adns: c-ares 1.18.1
tls: OpenSSL 3.0.2 15 Mar 2022
systemd: yes
```

in docker image: timescale/timescaledb-ha:pg15.6-ts2.14.0-all

```
:55024 FIXME: query end, but query_start == 0
:39326 FIXME: query end, but query_start == 0
36968 FIXME: query end, but query_start == 0
610 FIXME: query end, but query_start == 0
3466 FIXME: query end, but query_start == 0
35890 FIXME: query end, but query_start == 0
:33648 FIXME: query end, but query_start == 0
6108 FIXME: query end, but query_start == 0
36928 FIXME: query end, but query_start == 0
:54078 FIXME: query end, but query_start == 0
400 FIXME: query end, but query_start == 0
3466 FIXME: query end, but query_start == 0
40978 FIXME: query end, but query_start == 0
60860 FIXME: query end, but query_start == 0
610 FIXME: query end, but query_start == 0
36938 FIXME: query end, but query_start == 0
39352 FIXME: query end, but query_start == 0
35910 FIXME: query end, but query_start == 0
:54084 FIXME: query end, but query_start == 0
610 FIXME: query end, but query_start == 0
:55032 FIXME: query end, but query_start == 0
:39340 FIXME: query end, but query_start == 0
34610 FIXME: query end, but query_start == 0
:54082 FIXME: query end, but query_start == 0
400 FIXME: query end, but query_start == 0
```

### PR DESCRIPTION
**Pull request by JelteF**
In #845 full tracking of expected responses was implemented. This turned out to have bugs when sending `COPY FROM STDIN` queries using the extended protocol. [The protocol explicitly allows sending `Sync` messages after sending an `Execute` message for a `COPY FROM STDIN` command][1]. Such Sync messages are ignored by the server until a CopyDone or CopyFail message is received. The new command queue tracking did not take this into account, and was incorrectly expecting more ReadyForQuery messages from the server.

This could lead to two problems for the server connection on which the `COPY FROM STDIN` was sent:
1. The server connection would never be unassigned from the client.
2. Memory usage for this server connection would continue to increase until the client disconnects.
3. If `max_prepared_statements` was non-zero, then clients might receive ParseComplete and CloseComplete responses in the wrong order. This wouldn't result in wrong behaviour by the server, but the client might get confused and close the connection.

This PR fixes these issues. It also removes the rfq_count tracking, since it's now only keeping track of a strict subset of what the outstanding request queue was tracking.

[1]: https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-COPY

Fixes #1023
Fixes #1024

### CODE REVIEW

File: src/server.c [hunk 1]
```diff
@@ -358,11 +350,23 @@ static bool handle_server_work(PgSocket *server, PktHdr *pkt)
...
+			 * It isn't a problem if the CopyDone or CopyFail
+			 * message has not been received yet. This message will
+			 * be removed from the queue later when the server
+			 * sends a ReadyForQuery message and we clear the queue
+			 * until the next Sync.
+			 */
+			if (!clear_outstanding_requests_until(server, "cf"))
+				return false;
 		} else {
 			server->query_failed = true;
```
Comment (JelteF) [inline src/server.c:371]: This should happen always probably, otherwise we won't pop a later received CopyDone message in case of failure.

File: test/conftest.py [hunk 2]
```diff
@@ -136,6 +136,9 @@ def pg(tmp_path_factory, cert_dir):
     pg.sql(f"create user longpass with password '{LONG_PASSWORD}';")
     pg.sql("create user stats password 'stats';")
     pg.sql("grant all on schema public to public", dbname="p0")
+    pg.sql("create table t(i int)", dbname="p0")
+    pg.sql("grant all on table t to public", dbname="p0")
+
```
Comment (eulerto) [inline test/conftest.py:141]: Rename table "t" to "test_copy". It seems clear that it is used by `test_copy.py`.

**Review by eulerto — CHANGES_REQUESTED** [review]
LGTM. Don't forget to include test_copy.py into EXTRA_DIST target (I submitted another PR #1026 that included some recent tests into it.)

**Comment by eulerto** [comment]
There are some tests that still refers to table "t".

**Review by eulerto — APPROVED** [review]
LGTM
